version: '3.3'

volumes:
  db:
  static:
  media:

services:

  frontend:
    image: andreytsay/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - db:/var/lib/postgresql/data
    depends_on:
      - frontend
  backend:
    image: andreytsay/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static/
      - media:/media/
    depends_on:
      - frontend
      - db
  nginx:
    image: nginx:1.19.3
    ports:
      - '9090:80'
    volumes:
      - ../frontend/build:/usr/share/nginx/html/ 
      - static:/static/
      - media:/media/
    depends_on:
      - frontend
      - db
      - backend