version: '3.3'

volumes:
  foodgram_data:
  foodgram_static:
  foodgram_media:

services:

  foodgram_db:
    image: postgres:13
    env_file: .env
    volumes:
      - foodgram_data:/var/lib/postgresql/data
  
  backend:
    image: andreytsay/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static/
      - media:/media/ 
    depends_on:
      - foodgram_db

  frontend:
    image: andreytsay/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - 9090:80
    volumes:
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/staticfiles/ 
      - media:/media/ 
    depends_on:
      - backend
      - frontend